name: flutter_cache_manager
description: Generic cache manager for flutter. Saves web files on the storages of the device and saves the cache info using sqflite.
version: 1.1.3
author: Rene Floor <pub@renefloor.nl>
homepage: https://github.com/renefloor/flutter_cache_manager

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.8
  uuid:  "^2.0.0"
  http: ">=0.11.0 < 0.13.0"
  hive: ^1.4.0+1

dev_dependencies:
  hive_generator: ^0.7.0
  build_runner: ^1.7.4
  flutter_test:
    sdk: flutter
  test: "^1.3.0"
